---
apiVersion: v1
kind: Namespace
metadata:
  name: codeserver

---
apiVersion: v1
kind: Secret
metadata:
  name: code-server-secret
  namespace: codeserver
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=         # "password" encoded in base64
  SUDO_PASSWORD: cGFzc3dvcmQ=   # "password" encoded in base64

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server-config
  namespace: codeserver
data:
  TZ: Asia/Singapore
  PROXY_DOMAIN: code-144.126.240.77.nip.io  # Replace <IP> with actual IP address
  DEFAULT_WORKSPACE: /config/workspace
