---
apiVersion: v1
kind: Namespace
metadata:
  name: bggns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-db-config
  namespace: bggns
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-db-secret
  namespace: bggns
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaxQ=  # "changeit" in base64 encoding
