---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgg-database
  namespace: bggns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg-database
  template:
    metadata:
      labels:
        app: bgg-database
    spec:
      containers:
      - name: bgg-database
        image: stackupiss/bgg-database:v1
        envFrom:
        - configMapRef:
            name: bgg-db-config
        - secretRef:
            name: bgg-db-secret
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: bgg-database

