---
apiVersion: v1
kind: Namespace
metadata:
  name: s3ns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: s3ns
data:
  MINIO_ROOT_USER: minio_admin
  MINIO_DATA_DIR: /data
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
  MINIO_DISTRIBUTED_NODES: minio-sts-{0...3}.minio-hsvc.s3ns.svc.cluster.local/data
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: s3ns
type: Opaque
data:
  MINIO_ROOT_PASSWORD: bWluaW9fcGFzc3dvcmQ=         # "minio_password" encoded in base64

